### ISSUE TITLE
Pridanie pacienta

### ISSUE THREAD

**Issue by MichalToth5** [MichalToth5/3-peaks_frontEnd#1]
Ako používateľ chcem vedieť pridávať nových pacientov.

Budú zobrazené textové polia, do ktorých budeme zadávať údaje:
- krstné meno
- priezvisko
- rodné číslo
- dátum narodenia
- pohlavie
- telefónne číslo
- email
- poisťovňa
- ulica, číslo domu, mesto, štát

Nižšie budú tlačidlá "pridaj" a "zruš".
Optional TODO:

- [ ] Na stránke bude taktiež tlačidlo "späť", ktoré vracia do hlavného menu.

**Comment by aulinka** [comment]
hi @MichalToth5

**Comment by aulinka** [comment]
obrazok:
![image](https://user-images.githubusercontent.com/75043905/160478163-7acf5240-2b64-4305-8138-a636cb63e86a.png)

**Comment by aulinka** [comment]
commmit
[77f1e3d6c711b31c75ab9db256b6d8bda8ad5bac](https://github.com/MichalToth5/3-peaks_backEnd/commit/77f1e3d6c711b31c75ab9db256b6d8bda8ad5bac)
