### ISSUE TITLE
Pridanie vakcíny

### ISSUE THREAD

**Issue by AnetaSzolikova** [MichalToth5/3-peaks_frontEnd#3]
Ako používateľ chcem pridávať vakcíny do databázy vakcín.
V hlavnom menu kde kliknem na záložku "Vakcíny", zobrazí sa list vakcín a tlačidlo "Pridať Vakcínu" na ktoré keď kliknem otvorí sa formulár obsahujúci: 
- názov vakcíny
- typ
- výrobca
- dni ďalšej dávky
- minimálny a maximálny vek

Pod formulárom bude tlačidlo "Pridať vakcínu" a "Zrušiť". Tlačidlo "Pridať vakcínu" uloží zadané dáta a pridá do databázy vakcín. Tlačidlo "Zrušiť" vymaže zadané údaje.
Optional TODO: 
- [ ] Na stránke sa taktiež bude nachádzať tlačidlo "Späť", ktoré vráti používateľa do hlavného menu.

**Comment by aulinka** [comment]
obrazok:
![image](https://user-images.githubusercontent.com/75043905/160478050-bd1f8c18-a835-47fe-a8b3-0840b2e49308.png)

**Comment by aulinka** [comment]
commmit
[77f1e3d6c711b31c75ab9db256b6d8bda8ad5bac](https://github.com/MichalToth5/3-peaks_backEnd/commit/77f1e3d6c711b31c75ab9db256b6d8bda8ad5bac)
